spring.application.name=acs-service

#Local Oracle Database Configuration
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLCDB
#spring.datasource.username=SYS
#spring.datasource.password=mypassword1
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.hikari.data-source-properties.internal_logon=SYSDBA

#AWS RDS Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@orcledbins1.chkeq8k26ofx.us-west-2.rds.amazonaws.com:1521/ORCL
spring.datasource.username=admin
spring.datasource.password=VMware123!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver



spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true